name: Epic Games
on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Claimer
        run: |
          docker run --rm \
          --entrypoint node \
          -e EG_EMAIL="${{ secrets.EG_EMAIL }}" \
          -e EG_PASSWORD="${{ secrets.EG_PASSWORD }}" \
          -v $(pwd)/data:/claimer/data \
          ghcr.io/vogler/free-games-claimer out/index.js epicgames --no-vnc
