name: Epic Games
on:
  workflow_dispatch:

jobs:
  claim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Claimer
        run: |
          docker run --rm \
          -e EG_EMAIL="${{ secrets.EG_EMAIL }}" \
          -e EG_PASSWORD="${{ secrets.EG_PASSWORD }}" \
          ghcr.io/vogler/free-games-claimer node epic-games.js --no-vnc --skip-launcher-update
